import type { Project } from "@arcdev/shared";

// Real ArcDev projects, drawn from the company's portfolio deck.
// Figures (land area, built area, storeys, units) are as stated in that deck;
// ArcDev should confirm exact unit counts and handover dates before they're quoted to leads.
export const PROJECTS: Project[] = [
  {
    slug: "imperial-commercial-center",
    name: "Imperial Commercial Center",
    location: "Satmasjid Road, Dhaka",
    status: "ongoing",
    kind: "commercial",
    summary: "A 13-storey commercial tower on Satmasjid Road, two basements and a landscaped roof terrace.",
    description:
      "Imperial Commercial Center rises 13 storeys over two basement levels on a 17-katha plot, one of ArcDev's largest commercial buildings to date. The glass-and-brick facade wraps a full-floor lobby, with a rooftop garden and helipad marking the crown of the building.",
    landKatha: 17,
    storeys: 13,
    flatSizesSqft: [11159],
    amenities: ["Two basement parking levels", "Rooftop garden", "Helipad", "Full glass facade", "Passenger and service lifts"],
    images: [
      "/images/projects/imperial-commercial-center/exterior-01.webp",
      "/images/projects/imperial-commercial-center/exterior-02.webp",
      "/images/projects/imperial-commercial-center/street-view-01.webp",
      "/images/projects/imperial-commercial-center/facade-detail-01.webp",
      "/images/projects/imperial-commercial-center/aerial-01.webp",
    ],
  },
  {
    slug: "joynal-garden",
    name: "Joynal Garden",
    location: "Elephant Road, Dhaka",
    status: "ongoing",
    kind: "commercial",
    summary: "A ten-storey commercial building on a corner plot at Elephant Road, with a basement and a planted terrace.",
    description:
      "Joynal Garden sits on a 5-katha corner plot at Elephant Road: one basement plus ten storeys of brick-and-glass commercial space, with double-height ground-floor retail and a landscaped setback that softens the street frontage.",
    landKatha: 5,
    storeys: 10,
    flatSizesSqft: [1254],
    amenities: ["Basement parking", "Double-height ground floor", "Landscaped frontage", "Passenger lift"],
    images: [
      "/images/projects/joynal-garden/exterior-01.webp",
      "/images/projects/joynal-garden/entrance-01.webp",
      "/images/projects/joynal-garden/exterior-02.webp",
      "/images/projects/joynal-garden/rooftop-01.webp",
    ],
  },
  {
    slug: "runner-apartment-complex",
    name: "Runner Apartment Complex",
    location: "Dhaka",
    status: "completed",
    kind: "residential",
    summary: "A nine-storey riverside apartment building with a rooftop garden and a glazed ground-floor pavilion.",
    description:
      "Built on a 5.218-katha plot, Runner Apartment Complex rises one basement plus ground and eight storeys, its brick-and-glass balconies looking over the water. The ground floor opens into a glazed common pavilion and drop-off court, with a planted roof terrace shared by residents.",
    landKatha: 5.218,
    storeys: 9,
    amenities: ["Rooftop garden", "Glazed common pavilion", "Riverside frontage", "Covered parking", "Passenger lift"],
    images: [
      "/images/projects/runner-apartment-complex/exterior-riverside-01.webp",
      "/images/projects/runner-apartment-complex/aerial-01.webp",
      "/images/projects/runner-apartment-complex/exterior-01.webp",
      "/images/projects/runner-apartment-complex/exterior-02.webp",
      "/images/projects/runner-apartment-complex/exterior-03.webp",
      "/images/projects/runner-apartment-complex/walkway-01.webp",
      "/images/projects/runner-apartment-complex/rooftop-terrace-01.webp",
      "/images/projects/runner-apartment-complex/interior-living-01.webp",
    ],
  },
  {
    slug: "swadesh-sunvalley",
    name: "Swadesh Sunvalley",
    location: "Sun Valley Abashan, Road 4A, Block D, Plot 246, Dhaka",
    status: "ongoing",
    kind: "residential",
    summary: "A ten-storey apartment tower over ground floor, built around a landscaped courtyard.",
    description:
      "Swadesh Sunvalley is a ground-plus-nine residential tower in Sun Valley Abashan, its brick-clad blocks arranged around a shared courtyard with a rooftop pavilion for residents to gather.",
    storeys: 9,
    amenities: ["Landscaped courtyard", "Rooftop pavilion", "Covered parking", "Passenger lift"],
    images: ["/images/projects/swadesh-sunvalley/exterior-night-01.webp"],
  },
  {
    slug: "habitus-fashion",
    name: "Habitus Fashion Ltd",
    location: "Rajendropur, Gazipur",
    status: "completed",
    kind: "industrial",
    summary: "A six-storey, 60,000 sq ft garment factory built with an in-house engineering team.",
    description:
      "Habitus Fashion Ltd's factory in Rajendropur spans six storeys and 60,000 square feet, delivered alongside the client's own indigenous engineering team. Wide floor plates, a reflecting water feature at the entrance and generous glazing bring daylight deep into the production floors.",
    storeys: 6,
    flatSizesSqft: [60000],
    amenities: ["60,000 sq ft floor space", "Reflecting entrance pool", "Wide-span production floors", "Built with client's own engineering team"],
    images: [
      "/images/projects/habitus-fashion/exterior-01.webp",
      "/images/projects/habitus-fashion/exterior-lawn-01.webp",
      "/images/projects/habitus-fashion/exterior-02.webp",
      "/images/projects/habitus-fashion/water-reflection-01.webp",
      "/images/projects/habitus-fashion/walkway-01.webp",
      "/images/projects/habitus-fashion/garden-view-01.webp",
      "/images/projects/habitus-fashion/walkway-02.webp",
      "/images/projects/habitus-fashion/interior-lobby-01.webp",
    ],
  },
  {
    slug: "appropriate-apparels",
    name: "Appropriate Apparels Ltd",
    location: "Kuchakori, Kamrangirchala",
    status: "ongoing",
    kind: "industrial",
    summary: "A three-storey, 30,000 sq ft apparel factory currently under construction.",
    description:
      "Appropriate Apparels Ltd's new factory at Kuchakori, Kamrangirchala is being built with the client's own indigenous team: three storeys totalling 30,000 square feet, designed for efficient production-line layouts and natural light.",
    storeys: 3,
    flatSizesSqft: [30000],
    amenities: ["30,000 sq ft floor space", "Built with client's own engineering team"],
    images: [
      "/images/projects/appropriate-apparels/render-01.webp",
      "/images/projects/appropriate-apparels/construction-01.webp",
      "/images/projects/appropriate-apparels/render-02.webp",
      "/images/projects/appropriate-apparels/render-03.webp",
    ],
  },
  {
    slug: "sadma-fashion-dyeing",
    name: "Sadma Fashion Dyeing",
    location: "Kuchakori, Nobuarbag, Mouchak",
    status: "ongoing",
    kind: "industrial",
    summary: "A six-storey, 60,000 sq ft dyeing and fashion facility under construction.",
    description:
      "Sadma Fashion Dyeing's plant at Kuchakori, Nobuarbag, Mouchak is under construction: six storeys and 60,000 square feet, built with the client's own indigenous engineering team.",
    storeys: 6,
    flatSizesSqft: [60000],
    amenities: ["60,000 sq ft floor space", "Built with client's own engineering team"],
    images: [
      "/images/projects/sadma-fashion-dyeing/construction-01.webp",
      "/images/projects/sadma-fashion-dyeing/construction-02.webp",
      "/images/projects/sadma-fashion-dyeing/construction-03.webp",
    ],
  },
  {
    slug: "desco-chq-nikunjo",
    name: "Desco CHQ",
    location: "Nikunjo-1, Dhaka",
    status: "upcoming",
    kind: "commercial",
    summary: "A proposed 12-storey headquarters building submitted for a design competition.",
    description:
      "Desco CHQ is ArcDev's competition entry for a new 12-storey corporate headquarters on a 1.5-bigha plot at Nikunjo-1, wrapped in a brise-soleil screen that shades the glazed office floors and steps back at the crown into a rooftop garden.",
    storeys: 12,
    flatSizesSqft: [13500],
    amenities: ["Brise-soleil sun screen", "Rooftop garden", "Competition design entry"],
    images: [
      "/images/projects/desco-chq-nikunjo/render-terrace-01.webp",
      "/images/projects/desco-chq-nikunjo/render-aerial-01.webp",
      "/images/projects/desco-chq-nikunjo/render-night-01.webp",
    ],
  },
  {
    slug: "anlima-purbachal",
    name: "Anlima Vacation House",
    location: "Purbachal, Dhaka",
    status: "completed",
    kind: "hotel-resort",
    summary: "A brick-and-timber vacation house on 12 bigha at Purbachal, built around a private lake.",
    description:
      "Anlima Vacation House sits on 12 bigha of land at Purbachal, its perforated brick screens and deep timber eaves opening onto a private lake. Sliding glass walls fold back the dining and living pavilions to the water, with roughly 7,000 square feet of covered floor area across the main house and guest pavilions.",
    landKatha: 240,
    flatSizesSqft: [7000],
    amenities: ["Private lake frontage", "Folding glass pavilions", "Perforated brick screens", "Outdoor pool", "Guest pavilions"],
    images: [
      "/images/projects/anlima-purbachal/lake-view-01.webp",
      "/images/projects/anlima-purbachal/exterior-day-01.webp",
      "/images/projects/anlima-purbachal/entrance-night-01.webp",
      "/images/projects/anlima-purbachal/pool-render-01.webp",
      "/images/projects/anlima-purbachal/pool-lilies-01.webp",
      "/images/projects/anlima-purbachal/dining-hall-01.webp",
      "/images/projects/anlima-purbachal/dining-render-01.webp",
      "/images/projects/anlima-purbachal/brick-walkway-01.webp",
      "/images/projects/anlima-purbachal/bedroom-render-01.webp",
    ],
  },
  {
    slug: "hai-residence-noakhali",
    name: "Hai Residence",
    location: "Noakhali",
    status: "completed",
    kind: "residential",
    summary: "A 10,000 sq ft triplex family home in Noakhali, built around a reflecting courtyard pool.",
    description:
      "Hai Residence is a single-family triplex of roughly 10,000 square feet, its brick and timber volumes wrapped around a narrow reflecting pool that runs through the courtyard. Full-height timber-framed glazing opens every living space onto the garden, with a planted rooftop and mature landscaping throughout the grounds.",
    flatSizesSqft: [10000],
    amenities: ["Courtyard reflecting pool", "Full-height timber glazing", "Planted rooftop", "Mature private garden", "Triplex layout"],
    images: [
      "/images/projects/hai-residence-noakhali/courtyard-pool-01.webp",
      "/images/projects/hai-residence-noakhali/courtyard-pool-02.webp",
      "/images/projects/hai-residence-noakhali/exterior-facade-01.webp",
      "/images/projects/hai-residence-noakhali/exterior-green-facade-01.webp",
      "/images/projects/hai-residence-noakhali/living-room-01.webp",
      "/images/projects/hai-residence-noakhali/living-room-double-height-01.webp",
      "/images/projects/hai-residence-noakhali/staircase-01.webp",
      "/images/projects/hai-residence-noakhali/garden-01.webp",
      "/images/projects/hai-residence-noakhali/bathroom-tub-01.webp",
      "/images/projects/hai-residence-noakhali/bathroom-vanity-01.webp",
    ],
  },
  {
    slug: "cafe-red-beret",
    name: "Cafe Red Beret",
    location: "Army MP Unit, Cantonment, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A riverside brick-and-timber cafe pavilion for the Army MP Unit, designed with Induscon.",
    description:
      "Cafe Red Beret is a low brick pavilion under a folded steel roof, built along the cantonment's lakeside walkway. Full-height glazing and a mirrored feature wall open the dining room to the water on both sides, with an outdoor stone-paved terrace for open-air seating. Designed jointly with Induscon Architects, Engineers, Planners and Interior Designers.",
    amenities: ["Lakeside terrace seating", "Full-height glazing", "Mirrored feature wall", "Outdoor stone terrace"],
    images: [
      "/images/projects/cafe-red-beret/exterior-riverside-01.webp",
      "/images/projects/cafe-red-beret/exterior-riverside-02.webp",
      "/images/projects/cafe-red-beret/walkway-01.webp",
      "/images/projects/cafe-red-beret/render-exterior-01.webp",
      "/images/projects/cafe-red-beret/render-terrace-01.webp",
      "/images/projects/cafe-red-beret/render-interior-01.webp",
      "/images/projects/cafe-red-beret/render-exterior-02.webp",
    ],
  },
  {
    slug: "royal-group-head-office",
    name: "Royal Group Head Office",
    location: "Navana Nasrin Casabela, Gulshan-2, North Avenue Road, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A 3,100 sq ft head-office interior on the sixth floor, workstations, meeting rooms and reception.",
    description:
      "Royal Group's 3,100 square foot head office on the sixth floor of Navana Nasrin Casabela in Gulshan-2 was designed and fitted out by ArcDev's ARCTIC interior studio, from open-plan workstations and glazed meeting rooms to the branded reception.",
    flatSizesSqft: [3100],
    amenities: ["Open-plan workstations", "Glazed meeting rooms", "Branded reception", "Custom joinery"],
    images: [
      "/images/projects/royal-group-head-office/executive-office-01.webp",
      "/images/projects/royal-group-head-office/reception-01.webp",
      "/images/projects/royal-group-head-office/workstations-01.webp",
      "/images/projects/royal-group-head-office/lounge-01.webp",
      "/images/projects/royal-group-head-office/boardroom-01.webp",
      "/images/projects/royal-group-head-office/meeting-room-01.webp",
    ],
  },
  {
    slug: "royal-group-branch-office",
    name: "Royal Group Branch Office",
    location: "Banani Bl-K, House 28, Road 28, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A 1,700 sq ft branch office fit-out in Banani, workstations and storage.",
    description: "A 1,700 square foot branch office for Royal Group in Banani, fitted with open workstations, storage cabinetry and a compact meeting corner.",
    flatSizesSqft: [1700],
    images: [
      "/images/projects/royal-group-branch-office/interior-01.webp",
      "/images/projects/royal-group-branch-office/interior-02.webp",
      "/images/projects/royal-group-branch-office/interior-03.webp",
    ],
  },
  {
    slug: "royal-group-guest-house",
    name: "Royal Group Guest House",
    location: "Banani DOHS, House 60, Road 4A, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "An 1,800 sq ft guest house interior, living, dining and bedrooms fully furnished.",
    description:
      "Royal Group's 1,800 square foot guest house on Road 4A, Banani DOHS was designed end to end by ArcDev: open kitchen and breakfast bar, layered living and dining spaces, and bedrooms finished with custom joinery and statement lighting.",
    flatSizesSqft: [1800],
    amenities: ["Open kitchen and breakfast bar", "Custom furniture and joinery", "Statement lighting", "Fully furnished bedrooms"],
    images: [
      "/images/projects/royal-group-guest-house/kitchen-bar-01.webp",
      "/images/projects/royal-group-guest-house/bedroom-01.webp",
      "/images/projects/royal-group-guest-house/living-room-01.webp",
      "/images/projects/royal-group-guest-house/kitchen-01.webp",
      "/images/projects/royal-group-guest-house/sitting-area-01.webp",
      "/images/projects/royal-group-guest-house/sitting-corner-01.webp",
    ],
  },
  {
    slug: "dept-of-management-du",
    name: "Department of Management, University of Dhaka",
    location: "University of Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A 1,418 sq ft administrative office renovation for the Department of Management.",
    description:
      "ArcDev's ARCTIC studio renovated the 1,418 square foot administrative office for the Department of Management at the University of Dhaka: perforated timber screens, a quotation-lined boardroom and glazed private offices, finished within the constraints of a working academic building.",
    flatSizesSqft: [1418],
    amenities: ["Perforated timber screening", "Glazed private offices", "Boardroom with feature wall graphics"],
    images: [
      "/images/projects/dept-of-management-du/nameplate-01.webp",
      "/images/projects/dept-of-management-du/exterior-facade-01.webp",
      "/images/projects/dept-of-management-du/entrance-hallway-01.webp",
      "/images/projects/dept-of-management-du/boardroom-01.webp",
      "/images/projects/dept-of-management-du/corridor-01.webp",
      "/images/projects/dept-of-management-du/meeting-room-01.webp",
      "/images/projects/dept-of-management-du/office-desk-01.webp",
    ],
  },
  {
    slug: "newtex-group",
    name: "Newtex Group Head Office",
    location: "Suvastu Tower, Panthapath, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A garment-industry head office and showroom interior at Suvastu Tower, Panthapath.",
    description: "Newtex Group's head office interior at Suvastu Tower, Panthapath pairs an executive suite and boardroom with an in-house apparel showroom, timber slat ceilings and reception in dark, warm tones.",
    amenities: ["Executive suite", "In-house apparel showroom", "Boardroom", "Timber slat ceilings"],
    images: [
      "/images/projects/newtex-group/meeting-room-showcase-01.webp",
      "/images/projects/newtex-group/lounge-01.webp",
      "/images/projects/newtex-group/reception-01.webp",
      "/images/projects/newtex-group/corridor-01.webp",
      "/images/projects/newtex-group/office-nook-01.webp",
    ],
  },
  {
    slug: "oredh-studio",
    name: "OREDH Render Studio & Lounge",
    location: "247-248, Tejgaon I/A, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A second-floor render studio and adjoining bamboo-screened lounge in Tejgaon.",
    description:
      "OREDH's studio floor at Tejgaon I/A combines an open render workstation bay with a materials library, and steps out onto a bamboo-screened lounge terrace lit for evening use.",
    amenities: ["Open workstation bay", "Materials library", "Bamboo-screened terrace lounge"],
    images: [
      "/images/projects/oredh-studio/studio-interior-01.webp",
      "/images/projects/oredh-studio/lounge-01.webp",
      "/images/projects/oredh-studio/studio-interior-02.webp",
      "/images/projects/oredh-studio/studio-interior-03.webp",
      "/images/projects/oredh-studio/entrance-signage-01.webp",
      "/images/projects/oredh-studio/decor-detail-01.webp",
    ],
  },
  {
    slug: "best-in-brands",
    name: "Best In Brands Showroom",
    location: "Banani Road 12, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A multi-brand perfume and cosmetics retail fit-out for Sundora, Penhaligon's and other houses.",
    description:
      "The Best In Brands outlet on Banani Road 12 fits several international perfume and cosmetics houses — Sundora, Penhaligon's and more — into one dark, gallery-lit retail floor with brand-specific display bays and a central feature counter.",
    amenities: ["Multi-brand display bays", "Gallery lighting", "Central feature counter"],
    images: [
      "/images/projects/best-in-brands/showroom-wide-01.webp",
      "/images/projects/best-in-brands/display-tower-01.webp",
      "/images/projects/best-in-brands/sundora-counter-01.webp",
      "/images/projects/best-in-brands/sundora-counter-02.webp",
      "/images/projects/best-in-brands/penhaligons-display-01.webp",
      "/images/projects/best-in-brands/perfume-shelf-01.webp",
    ],
  },
  {
    slug: "dark-burg",
    name: "Dark Burg",
    location: "Mirpur DOHS & Mirpur 12, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "Two quick-service burger outlet fit-outs, at Daruchini Food Village and Signature Food Court.",
    description:
      "Dark Burg's two outlets — Daruchini Food Village at Mirpur DOHS Gate 1, and Signature Food Court at Mirpur 12 — pair a bold graphic brand identity with compact, efficient counter-service kitchens and casual seating.",
    amenities: ["Branded counter and signage", "Compact service kitchen", "Casual seating"],
    images: [
      "/images/projects/dark-burg/outlet-02-signage-01.webp",
      "/images/projects/dark-burg/outlet-01-counter-01.webp",
      "/images/projects/dark-burg/outlet-01-interior-01.webp",
      "/images/projects/dark-burg/outlet-02-decor-01.webp",
      "/images/projects/dark-burg/outlet-02-mural-01.webp",
    ],
  },
  {
    slug: "bongobondhu-corner",
    name: "Bongobondhu Corner",
    location: "Bangladesh Betar, Agargaon, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A commemorative corner display at Bangladesh Betar, backlit portrait and archive cases.",
    description: "A commemorative display corner at Bangladesh Betar (Bangladesh Radio), Agargaon: a backlit portrait, engraved furniture and glazed archive cases set beneath a suspended lighting grid.",
    images: [
      "/images/projects/bongobondhu-corner/installation-01.webp",
      "/images/projects/bongobondhu-corner/sitting-corner-01.webp",
      "/images/projects/bongobondhu-corner/portrait-detail-01.webp",
      "/images/projects/bongobondhu-corner/table-engraving-01.webp",
    ],
  },
  {
    slug: "office-interior",
    name: "Office Interior",
    location: "Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A 23,670 sq ft corporate office fit-out completed over an eight-month programme.",
    description: "A large-format corporate office interior of 23,670 square feet, delivered over an eight-month programme: open workstation floors, meeting suites and a break-out lounge.",
    flatSizesSqft: [23670],
    images: ["/images/projects/office-interior/workspace-01.webp", "/images/projects/office-interior/reception-lounge-01.webp"],
  },
  {
    slug: "babui-properties",
    name: "Babui Properties",
    location: "Elephant Road, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A 2,000 sq ft office interior on Elephant Road, reception through to private cabins.",
    description: "Babui Properties' 2,000 square foot office on Elephant Road was fitted out with a slatted-timber reception screen, glazed private cabins and a dark, understated material palette throughout.",
    flatSizesSqft: [2000],
    images: [
      "/images/projects/babui-properties/reception-01.webp",
      "/images/projects/babui-properties/corridor-01.webp",
      "/images/projects/babui-properties/office-01.webp",
      "/images/projects/babui-properties/workspace-01.webp",
      "/images/projects/babui-properties/detail-01.webp",
    ],
  },
  {
    slug: "easy-buy-showroom",
    name: "Easy Buy Showroom",
    location: "Topical Rajia Market, Shantinagar, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A compact leather-goods showroom fit-out at Shantinagar.",
    description: "A compact retail showroom for the Easy Buy leather-goods brand at Topical Rajia Market, Shantinagar: display shelving, glass counters and a small fitting area within a tight footprint.",
    images: [
      "/images/projects/easy-buy-showroom/showroom-counter-01.webp",
      "/images/projects/easy-buy-showroom/display-shelves-01.webp",
      "/images/projects/easy-buy-showroom/product-display-01.webp",
    ],
  },
  {
    slug: "doors-showroom",
    name: "Doors Showroom",
    location: "Jamuna Future Park, Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A backlit signage wall and retail floor for the Doors clothing brand.",
    description: "A retail floor for the Doors clothing brand at Jamuna Future Park, anchored by an illuminated channel-letter sign wall. Completed in 2014.",
    handover: "2014",
    images: ["/images/projects/doors-showroom/signage-01.webp"],
  },
  {
    slug: "bhalogari",
    name: "Bhalogari Ltd Showroom",
    location: "Dhaka",
    status: "completed",
    kind: "interior",
    summary: "A 5,000 sq ft ground-floor car showroom with a glazed street frontage.",
    description: "Bhalogari Ltd's 5,000 square foot showroom occupies a full ground floor, its glazed frontage and lit signage giving the display cars full street visibility, with a private office suite to the rear.",
    flatSizesSqft: [5000],
    images: [
      "/images/projects/bhalogari/showroom-lobby-01.webp",
      "/images/projects/bhalogari/showroom-floor-01.webp",
      "/images/projects/bhalogari/signage-01.webp",
      "/images/projects/bhalogari/ceiling-detail-01.webp",
      "/images/projects/bhalogari/showroom-columns-01.webp",
    ],
  },
];
