import type { Project } from "@arcdev/shared";

// SAMPLE PROJECTS for the website mock-up. Names, figures, dates and photos are invented;
// the photos are CC0 stock (see public/images/sample/CREDITS.md) and do not show ArcDev buildings.
// Replace with ArcDev's real projects before launch.
export const PROJECTS: Project[] = [
  {
    slug: "arc-nilachal",
    name: "Arc Nilachal",
    location: "Bashundhara R/A, Dhaka",
    status: "ongoing",
    kind: "residential",
    summary: "Ten storeys of family apartments on a corner plot, with a rooftop garden and two lifts.",
    description:
      "Arc Nilachal is a joint development with the plot's three owners. Thirty-six apartments face south and east over a 30-foot road, with a ground-floor lobby, covered parking for every flat and a planted roof terrace shared by all residents.",
    landKatha: 7.5,
    storeys: 10,
    units: 36,
    flatSizesSqft: [1650, 1850],
    handover: "December 2027",
    progress: 62,
    amenities: ["Two passenger lifts", "Standby generator", "Rooftop garden", "Covered parking", "CCTV and security desk", "Gas and water connections"],
    updates: [
      { date: "August 2026", title: "Seventh-floor slab cast" },
      { date: "May 2026", title: "Brickwork started on floors 1–4" },
      { date: "January 2026", title: "Ground-floor structure complete" },
      { date: "July 2025", title: "Piling finished" },
    ],
    images: ["/images/sample/residential-tower.webp", "/images/sample/site-frame.webp", "/images/sample/site-tower-crane.webp", "/images/sample/site-concrete.webp"],
  },
  {
    slug: "arc-meghdoot",
    name: "Arc Meghdoot",
    location: "Uttara Sector 13, Dhaka",
    status: "ongoing",
    kind: "residential",
    summary: "Nine storeys near the lake, two apartments per floor and nearly finished.",
    description:
      "Built on a single owner's land under the Fund programme, Arc Meghdoot has two apartments on each floor so every flat gets cross-ventilation. Finishing works are underway and the first flats are being fitted out.",
    landKatha: 5,
    storeys: 9,
    units: 16,
    flatSizesSqft: [1350, 1450],
    handover: "June 2027",
    progress: 78,
    amenities: ["Passenger lift", "Standby generator", "Children's play area", "Covered parking", "Intercom"],
    updates: [
      { date: "September 2026", title: "Lift installation underway" },
      { date: "June 2026", title: "External plaster and paint complete" },
      { date: "February 2026", title: "Roof slab cast" },
    ],
    images: ["/images/sample/hero-residential.webp", "/images/sample/site-workers.webp", "/images/sample/interior-kitchen-2.webp"],
  },
  {
    slug: "arc-shimul",
    name: "Arc Shimul",
    location: "Mirpur DOHS, Dhaka",
    status: "ongoing",
    kind: "residential",
    summary: "Foundations complete for eight storeys of compact family flats.",
    description:
      "A landshare project with five co-owners who inherited the plot. Piling is complete and the basement is being cast. Each owner's flats were allocated by lottery before construction began.",
    landKatha: 4,
    storeys: 8,
    units: 14,
    flatSizesSqft: [1200],
    handover: "March 2029",
    progress: 18,
    amenities: ["Passenger lift", "Standby generator", "Covered parking", "Rooftop drying area"],
    updates: [
      { date: "August 2026", title: "Basement raft casting started" },
      { date: "May 2026", title: "Piling complete" },
      { date: "February 2026", title: "Building approval received" },
    ],
    images: ["/images/sample/site-piling.webp", "/images/sample/site-crane.webp", "/images/sample/site-excavation.webp"],
  },
  {
    slug: "arc-bokul",
    name: "Arc Bokul",
    location: "Aftabnagar, Dhaka",
    status: "upcoming",
    kind: "residential",
    summary: "Twelve storeys planned on a 10-katha plot, now in design and approval.",
    description:
      "Arc Bokul will be ArcDev's largest residential building so far: forty-four apartments across twelve storeys, with a community hall and a gym. Designs are with the approval authority and bookings open once approval is received.",
    landKatha: 10,
    storeys: 12,
    units: 44,
    flatSizesSqft: [1100, 1300, 1550],
    handover: "Expected 2030",
    amenities: ["Three passenger lifts", "Community hall", "Gym", "Standby generator", "Covered parking", "Solar panels for common areas"],
    updates: [
      { date: "July 2026", title: "Approval drawings submitted" },
      { date: "April 2026", title: "Soil test completed" },
      { date: "January 2026", title: "Joint development agreement registered" },
    ],
    images: ["/images/sample/land-plot.webp", "/images/sample/land-planning.webp", "/images/sample/engineering-blueprint.webp"],
  },
  {
    slug: "arc-kashful",
    name: "Arc Kashful",
    location: "Dhanmondi, Dhaka",
    status: "completed",
    kind: "residential",
    summary: "Eleven storeys of large apartments, handed over and fully occupied.",
    description:
      "Arc Kashful replaced a 1970s two-storey house. The original owners kept eight of the twenty apartments; the rest were sold before completion. Interiors for six flats were designed and finished by ArcDev's interior team.",
    landKatha: 6,
    storeys: 11,
    units: 20,
    flatSizesSqft: [2100],
    handover: "August 2024",
    amenities: ["Two passenger lifts", "Standby generator", "Rooftop terrace", "Covered parking", "Reception and security"],
    images: ["/images/sample/tower-blue.webp", "/images/sample/interior-living.webp", "/images/sample/interior-kitchen.webp", "/images/sample/interior-bedroom.webp"],
  },
  {
    slug: "arc-business-point",
    name: "Arc Business Point",
    location: "Banani, Dhaka",
    status: "completed",
    kind: "commercial",
    summary: "Fourteen floors of offices with a glass facade, fully leased.",
    description:
      "A commercial building developed with two landowners and four investors. Offices are let floor by floor, with a showroom at street level and three basement floors of parking.",
    landKatha: 12,
    storeys: 14,
    units: 14,
    flatSizesSqft: [5200],
    handover: "March 2023",
    amenities: ["Four high-speed lifts", "Central air conditioning", "Three basement parking levels", "Full-load generator", "Fire detection and sprinklers"],
    images: ["/images/sample/glass-towers.webp", "/images/sample/city-night-towers.webp", "/images/sample/interior-open-plan.webp"],
  },
];
